spring:
  docker:
    compose:
      file: src/main/docker/compose.yml
      enabled: true
      lifecycle-management: start_only

  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: true


server:
  port: 8081


